"https://{default}/":
  type: upstream
  upstream: "callingallpapers_web:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"http://{default}/":
  type: redirect
  to: "https://{default}/"

"http://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/.well-known/host-meta":
  type: redirect
  to: "https://social.{default}/.well-known/host-meta"

"https://{default}/.well-known/webfinger":
  type: redirect
  to: "https://social.{default}/.well-known/webfinger"

"https://{default}/.well-known/nodeinfo":
  type: redirect
  to: "https://social.{default}/.well-known/nodeinfo"
